# Generated by Django 3.2.14 on 2022-12-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('page', models.CharField(blank=True, max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='product-images')),
                ('image_name', models.CharField(max_length=250)),
                ('tax_code', models.CharField(choices=[('G', 'txcd_99999999'), ('S', 'txcd_20030000'), ('H', 'txcd_10701100'), ('P', 'txcd_34021000'), ('B', 'txcd_35010000')], default='G', max_length=2)),
                ('cat', models.CharField(choices=[('B', 'Books'), ('S', 'Services'), ('M', 'Misc')], default='M', max_length=2)),
                ('mode', models.CharField(choices=[('P', 'payment'), ('S', 'subscription')], default='P', max_length=1)),
            ],
        ),
    ]
