# Generated by Django 3.2.14 on 2022-12-25 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('main', '0001_initial'), ('main', '0002_cartproduct'), ('main', '0003_alter_cart_products'), ('main', '0004_product_type'), ('main', '0005_product_description'), ('main', '0006_cartproduct_price_alter_cartproduct_quantity'), ('main', '0007_cartproduct_price_id_product_product_id'), ('main', '0008_auto_20221221_2101'), ('main', '0009_alter_product_external_product_id'), ('main', '0010_remove_cartproduct_price')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='data_here')),
                ('description', models.TextField(default='No description.')),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat', models.CharField(choices=[('B', 'Books'), ('S', 'Services'), ('E', 'Electronics'), ('M', 'Merch')], default='M', max_length=2)),
                ('external_product_id', models.CharField(blank=True, max_length=250, null=True)),
                ('image_name', models.CharField(blank=True, default='', max_length=250)),
                ('mode', models.CharField(choices=[('P', 'payment'), ('S', 'subscription')], default='P', max_length=1)),
                ('page', models.CharField(blank=True, max_length=250)),
                ('tax_code', models.CharField(choices=[('txcd_99999999', 'Goods'), ('txcd_20030000', 'Services'), ('txcd_10701100', 'Hosting'), ('txcd_34021000', 'Phones'), ('txcd_35010000', 'Books')], default='txcd_99999999', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='main.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('price_id', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(related_name='cart_products', to='main.cartproduct'),
        ),
    ]
