# Generated by Django 3.2.14 on 2022-12-26 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('price_id', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('description', models.TextField(default='No description.')),
                ('external_product_id', models.CharField(blank=True, max_length=250, null=True)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('page', models.CharField(blank=True, max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='data_here')),
                ('image_name', models.CharField(blank=True, default='', max_length=250)),
                ('tax_code', models.CharField(choices=[('txcd_99999999', 'Goods'), ('txcd_20030000', 'Services'), ('txcd_10701100', 'Hosting'), ('txcd_34021000', 'Phones'), ('txcd_35010000', 'Books')], default='txcd_99999999', max_length=20)),
                ('cat', models.CharField(choices=[('B', 'Books'), ('S', 'Services'), ('E', 'Electronics'), ('M', 'Merch')], default='M', max_length=2)),
                ('mode', models.CharField(choices=[('P', 'payment'), ('S', 'subscription')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('products', models.ManyToManyField(related_name='cart_products', to='main.CartProduct')),
            ],
        ),
    ]
