# Generated by Django 3.2.14 on 2022-12-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cartproduct_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='isbn',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='kickstarter',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='kindle_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
