# Generated by Django 3.2.14 on 2022-12-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20221228_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='kickstarter',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='kindle_link',
        ),
        migrations.AddField(
            model_name='product',
            name='isbn',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='kickstarter',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='kindle_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
