# Generated by Django 4.1.4 on 2023-01-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_auto_20221228_0527"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="preorder_only",
            field=models.BooleanField(default=False),
        ),
    ]
