# Generated by Django 4.1.4 on 2023-01-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_product_preorder_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="noorder",
            field=models.BooleanField(default=False),
        ),
    ]
