# Generated by Django 4.1.4 on 2023-01-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_product_noorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="backorder",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="date_available",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="upc",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
