# Generated by Django 3.2.14 on 2022-12-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20221221_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='external_product_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
