# Generated by Django 4.1.4 on 2023-01-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_product_backorder_product_brand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
