# Generated by Django 4.1.4 on 2023-01-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_product_sizes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="date_available",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="sizes",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
